<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "persons"
 *
 * Auto generated by Extension Builder 2017-05-15
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Persons',
    'description' => 'Manage persons',
    'category' => 'plugin',
    'author' => 'Dirk Wenzel',
    'author_email' => 'wenzel@cps-it.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
